### ISSUE TITLE
pick up framework and theme

### ISSUE THREAD

**Issue by lunebellec** [neurolibre/neurolibre.com#1]
for the framework, I am pretty much set on hugo. 

For the theme I am going to look.

**Comment by SamGuay** [comment]
Make sure to select a theme that has been updated recently (higher in the list of themes). Given that Hugo has been updating quite quickly in the last few weeks/months, a recent theme is more than advised to avoid surprises :upside_down_face:.

Also, if you are going for a theme with Bootstrap, favour Bootstrap 4 over Bootstrap 3. Will save many issues in the long run.

**Comment by lunebellec** [comment]
I am considering using https://themes.gohugo.io//theme/hugo-now-ui/components/
it's using bootstrap 4, but it hasn't been updated since last summer
https://github.com/cboettig/hugo-now-ui/commits/master

**Comment by lunebellec** [comment]
we've started the project with hugo-now-ui. We'll see how that goes.
