### ISSUE TITLE
organize posts

### ISSUE THREAD

**Issue by lunebellec** [neurolibre/neurolibre.com#5]
Currently we have two notebooks per column.
In the prototype, we use one notebook per column, and I think it looks much cleaner.

I suggest we start with a simple config file.
This config will need to be a bit more complicatied down the road for author affiliations, but it can come latter.
The notebook description would tentatively include date, tags, authors, title, summary, and image. 
These info would be pulled from files located in the `data/notebooks
each file `repo_name.yaml` would look like 
```
title: "The notebook"
summary: "A great notebook" 
authors: "Toto, Tata" 
date: "2020-03-26"
labels: "demo, neurolibre"
image: "img/notebooks/repo_name.png"
``` 

These data will be parsed from the template to populate the frontpage automatically. 
Here is an example of a partial (from universal theme) that does that
https://github.com/devcows/hugo-universal-theme/blob/232f219ee77aee3b539ed18417c02e328c3b4630/layouts/partials/recent_posts.html

I think our theme's equivalent of that is here:
https://github.com/cboettig/hugo-now-ui/blob/82c3eb002378e2ba774b89a3f5b853c039cbaeb7/layouts/_default/list.html
But it's much more rudimentary. 

We can start a new partial and just add it in the landing page (check the partials blocks):
https://github.com/cboettig/hugo-now-ui/blob/82c3eb002378e2ba774b89a3f5b853c039cbaeb7/layouts/_default/baseof.html

**Comment by agahkarakuzu** [comment]
- [X]  I suggest we start with a simple config file.
- [X]  The notebook description would tentatively include date, tags, authors, title, summary, and image.
- [X] These info would be pulled from files located in the data/notebooks each file 
- [X] data will be parsed from the template to populate the frontpage automatically.

#8
